# FGSM-FUAP configuration for Tiny-ImageNet
name: fgsm_fuap
model: FeaturePreActResNet18
total_epoch: 100
scheduler: one_cycle
lr: 0.1
momentum: 0.9
weight_decay: 5e-4
label_smoothing: 0.4
weight_average: true
tau: 0.9995
scheduler_milestones: [90, 95]
scheduler_gamma: 0.1
uap_num: 200
class_num: 300
image_shape: [3, 64, 64]
eval_start: 0
momentum_decay: 0.3
lamda: 10
uap_eps: 0.0392156862745098