name: fgsm_pco
total_epoch: 100
scheduler: one_cycle
lr: 0.1
momentum: 0.9
weight_decay: 5e-4
label_smoothing: 0.4
weight_average: true
tau: 0.9995
scheduler_milestones: [90, 95]
scheduler_gamma: 0.1
factor: 0.6
beta: 1.5
lamda: 10
delta_init: random
training_shape: [50000, 3, 32, 32]
num_classes: 100